(()=>{
const go=document.getElementById('go'),result=document.getElementById('result');if(!go||!result)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b)=>Math.hypot((+a.lat-+b.lat)*111,(+a.lon-+b.lon)*104),walkMin=d=>Math.max(1,Math.round(d*1000/83)),key=(r,i)=>r+'|'+i,sl=s=>s?.name||s?.stop_name||s?.label||'Arrêt de bus';
let progressMarkers=[],liveWatch=null,livePlan=null,currentStep=0,tripLayers=[];
function sp(s,ri,i){return{lat:+s.lat,lon:+s.lon,label:sl(s),route:ri,i}}
function graph(){const nodes=new Map(),edges=new Map(),all=[];routes.forEach((r,ri)=>(r.stops||[]).forEach((s,i)=>{const p=sp(s,ri,i);nodes.set(key(ri,i),{r:ri,i,s:p});edges.set(key(ri,i),[]);all.push(p)}));routes.forEach((r,ri)=>{for(let i=0;i<r.stops.length-1;i++){const a=sp(r.stops[i],ri,i),b=sp(r.stops[i+1],ri,i+1);edges.get(key(ri,i)).push({to:key(ri,i+1),kind:'bus',min:Math.max(1,Math.round(km(a,b)*1000/420))})}});for(const a of all)for(const b of all){if(a.route===b.route)continue;const d=km(a,b);if(d<=.45)edges.get(key(a.route,a.i))?.push({to:key(b.route,b.i),kind:'transfer',min:walkMin(d)+2,from:a,to:b})}return{nodes,edges}}
function nearest(p,limit=1.5){const o=[];routes.forEach((r,ri)=>(r.stops||[]).forEach((s,i)=>{const q=sp(s,ri,i),d=km(p,q);if(d<=limit)o.push({ri,i,p:q,d})}));return o.sort((a,b)=>a.d-b.d).slice(0,36)}
function routePlan(A,B){const g=graph(),starts=nearest(A),ends=nearest(B);if(!starts.length||!ends.length)return null;const dist=new Map(),prev=new Map(),q=[],endsSet=new Set(ends.map(x=>key(x.ri,x.i)));starts.forEach(x=>{const k=key(x.ri,x.i),c=walkMin(x.d);dist.set(k,c);q.push([c,k,0])});let target=null;while(q.length){q.sort((a,b)=>a[0]-b[0]);const[d,u,t]=q.shift();if(d!==dist.get(u))continue;if(endsSet.has(u)){target=u;break}if(t>4)continue;for(const e of g.edges.get(u)||[]){const nt=t+(e.kind==='transfer');if(nt>4)continue;const nd=d+e.min;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,{u,e});q.push([nd,e.to,nt])}}}if(!target)return null;const chain=[];let cur=target;while(cur){chain.push(cur);const p=prev.get(cur);if(!p)break;cur=p.u}chain.reverse();const end=ends.find(x=>key(x.ri,x.i)===target),first=g.nodes.get(chain[0]).s,last=g.nodes.get(chain.at(-1)).s;const seg=[{kind:'walk',from:A,to:first,min:walkMin(km(A,first)),m:Math.round(km(A,first)*1000)}];let leg=null;chain.forEach(k=>{const n=g.nodes.get(k);if(!leg||leg.route!==n.r){if(leg)seg.push(leg);leg={kind:'bus',route:n.r,stops:[n.s],min:0}}else leg.stops.push(n.s)});if(leg)seg.push(leg);for(let i=0;i<seg.length;i++)if(seg[i].kind==='bus'){const s=seg[i];s.min=Math.max(1,Math.round(s.stops.slice(0,-1).reduce((z,x,j)=>z+km(x,s.stops[j+1])*1000/420,0)));if(seg[i+1]?.kind==='bus'){const a=s.stops.at(-1),b=seg[i+1].stops[0];seg.splice(i+1,0,{kind:'transfer',from:a,to:b,min:walkMin(km(a,b)),m:Math.round(km(a,b)*1000)});i++}}seg.push({kind:'walk',from:last,to:B,min:walkMin(km(last,B)),m:Math.round(km(last,B)*1000)});return{segments:seg,totalMin:Math.max(1,Math.round((dist.get(target)||0)+walkMin(end.d)))} }
function clearTrip(){tripLayers.forEach(x=>{try{map.removeLayer(x)}catch{}});tripLayers=[];progressMarkers=[]}
function decode6(s){let i=0,la=0,lo=0,o=[];while(i<s.length){let b,sh=0,r=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<sh;sh+=5}while(b>=32);la+=r&1?~(r>>1):r>>1;sh=0;r=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<sh;sh+=5}while(b>=32);lo+=r&1?~(r>>1):r>>1;o.push([la/1e6,lo/1e6])}return o}
async function walkRoad(a,b){try{const r=await fetch('https://valhalla1.openstreetmap.de/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:[{lat:a.lat,lon:a.lon},{lat:b.lat,lon:b.lon}],costing:'pedestrian',units:'kilometers',shape_format:'polyline6'})});if(!r.ok)throw Error();const j=await r.json(),s=j?.trip?.legs?.[0]?.shape;return s?decode6(s):null}catch{return null}}
async function draw(plan){clearTrip();const all=[];for(const s of plan.segments){if(s.kind==='bus'){const pts=s.stops.map(x=>[x.lat,x.lon]);let road=null;try{road=await realRoad(pts)}catch{}const arr=road||pts;all.push(...arr);tripLayers.push(L.polyline(arr,{color:'#0072CE',weight:6,opacity:.95}).addTo(map));s.stops.forEach((x,i)=>{const m=L.circleMarker([x.lat,x.lon],{radius:5,weight:2,color:'#0072CE',fillColor:'#fff',fillOpacity:1}).addTo(map);m.bindTooltip((i+1)+' · '+x.label);progressMarkers.push(m)})}else{const pts=await walkRoad(s.from,s.to)||[[s.from.lat,s.from.lon],[s.to.lat,s.to.lon]];all.push(...pts);tripLayers.push(L.polyline(pts,{color:'#475467',weight:5,opacity:.9,dashArray:'9 9'}).addTo(map))}}if(all.length)map.fitBounds(L.latLngBounds(all),{padding:[70,70]})}
function title(s){if(s.kind==='walk')return'🚶 À pied';if(s.kind==='transfer')return'🔄 Correspondance';const r=routes[s.route]||{};return'🚌 Ligne '+(r.ref||'?')}
function showStep(i){if(!livePlan)return;currentStep=Math.max(0,Math.min(i,livePlan.segments.length-1));document.querySelectorAll('.stepChoice').forEach((b,j)=>{b.style.background=j===currentStep?'#eef6ff':'#fff';b.style.borderLeft=j===currentStep?'4px solid #0072CE':'4px solid transparent'});const s=livePlan.segments[currentStep];if(s.kind==='bus')map.setView([s.stops[0].lat,s.stops[0].lon],15);else map.setView([(s.from.lat+s.to.lat)/2,(s.from.lon+s.to.lon)/2],16);const x=document.getElementById('liveProgress');if(x)x.innerHTML='<b>Étape '+(currentStep+1)+' / '+livePlan.segments.length+' :</b> '+title(s)+'<br><span class="small">'+(s.kind==='bus'?esc(s.stops[0].label)+' → '+esc(s.stops.at(-1).label):esc(s.from.label)+' → '+esc(s.to.label))+'</span>'}
function render(plan){livePlan=plan;currentStep=0;const n=plan.segments.filter(s=>s.kind==='transfer').length;let h='<div class="big">⭐ Meilleur trajet · ~'+plan.totalMin+' min</div><div class="small">'+(n?n+' correspondance'+(n>1?'s':''):'Direct · 1 ligne')+'</div><button id="stepsBtn" class="btn" style="margin-top:10px;width:100%">🧭 Voir les étapes</button><div id="stepList" class="hidden">';plan.segments.forEach((s,i)=>{let d=s.kind==='bus'?((routes[s.route]?.from||'')+' → '+(routes[s.route]?.to||'')+' · '+s.stops.length+' arrêts · ~'+s.min+' min'):s.kind==='transfer'?('Marche '+s.min+' min · '+s.m+' m : '+s.from.label+' → '+s.to.label):(s.min+' min · '+s.m+' m : '+s.from.label+' → '+s.to.label);h+='<button class="step stepChoice" data-step="'+i+'" style="width:100%;text-align:left;background:#fff;border:0;border-bottom:1px solid #eee"><b>'+title(s)+'</b><div class="small">'+esc(d)+'</div></button>'});h+='</div><button id="trackBtn" class="follow">📍 Suivre ma progression</button><div id="liveProgress" class="progress">Choisis une étape ou démarre le suivi GPS.</div>';result.innerHTML=h;document.getElementById('stepsBtn').onclick=()=>{const x=document.getElementById('stepList');x.classList.toggle('hidden');document.getElementById('stepsBtn').textContent=x.classList.contains('hidden')?'🧭 Voir les étapes':'🧭 Masquer les étapes'};document.querySelectorAll('.stepChoice').forEach(b=>b.onclick=()=>showStep(+b.dataset.step));document.getElementById('trackBtn').onclick=()=>startTracking(plan)}
function nearestStop(p,s){let b=null;(s.stops||[]).forEach((x,i)=>{const d=km(p,x);if(!b||d<b.d)b={d,i,x}});return b}
function progress(pos){if(!livePlan)return;const p={lat:pos.coords.latitude,lon:pos.coords.longitude},s=livePlan.segments[currentStep];if(!s)return;let adv=false;if(s.kind==='bus'){const n=nearestStop(p,s);if(n&&n.i===s.stops.length-1&&n.d<.15)adv=true;progressMarkers.forEach((m,j)=>m.setStyle(j<=((n&&n.i)||0)?{fillColor:'#0072CE',color:'#0072CE'}:{fillColor:'#fff',color:'#0072CE'}))}else if(km(p,s.to)<.09)adv=true;if(adv&&currentStep<livePlan.segments.length-1)showStep(currentStep+1);const x=document.getElementById('liveProgress');if(x)x.innerHTML='<b>📍 Étape '+(currentStep+1)+' / '+livePlan.segments.length+'</b><br>'+title(livePlan.segments[currentStep])+(livePlan.segments[currentStep+1]?'<br><span class="small">Ensuite : '+title(livePlan.segments[currentStep+1])+'</span>':'');map.setView([p.lat,p.lon],16)}
function startTracking(plan){if(liveWatch!==null)navigator.geolocation.clearWatch(liveWatch);livePlan=plan;currentStep=0;showStep(0);if(!navigator.geolocation)return;liveWatch=navigator.geolocation.watchPosition(progress,()=>{const x=document.getElementById('liveProgress');if(x)x.textContent='⚠️ Suivi GPS indisponible. Vérifie la localisation Safari.'},{enableHighAccuracy:true,maximumAge:3000,timeout:12000});}
async function calc(){go.disabled=true;go.textContent='Recherche…';result.innerHTML='<b>🔎 Calcul de l’itinéraire…</b>';try{const A=await resolveInput($('from')),B=await resolveInput($('to'));if(!A||!B){result.innerHTML='<b class="err">📍 Départ ou destination introuvable.</b>';return}if(!routes?.length){result.innerHTML='<b class="err">Réseau bus indisponible.</b>';return}const p=routePlan(A,B);if(!p){result.innerHTML='<b>Aucun itinéraire trouvé.</b><div class="small">Aucun enchaînement de lignes à moins de 450 m entre les arrêts disponibles.</div>';return}await draw(p);render(p)}catch(e){console.error(e);result.innerHTML='<b class="err">Erreur de calcul</b><div class="small">'+esc(e.message||e)+'</div>'}finally{go.disabled=false;go.textContent='Trouver le meilleur trajet'}}
go.onclick=calc;window.calc=calc;
})();