(()=>{
const go=document.getElementById('go'),result=document.getElementById('result');if(!go||!result)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b)=>Math.hypot((a.lat-b.lat)*111,(a.lon-b.lon)*104);
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const R=[
 {ref:'123',from:'Port Louis Immigration',to:'Wolmar',operator:'NTC',stops:[
  ['Dragon Store',-20.2590,57.3970],['Flic en Flac Junction',-20.2820,57.3880],['Domaine Anna',-20.2860,57.3830],['Flic en Flac School',-20.27634,57.37281],['Flic en Flac Beach',-20.28896,57.36307],['Wolmar',-20.3069,57.3672]
 ].map((x,i)=>({name:x[0],lat:x[1],lon:x[2],i}))}
];
function gps(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,label:'Ma position'}),()=>resolve(null),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})})}
async function point(input){if(input.dataset.lat&&input.dataset.lon)return{lat:+input.dataset.lat,lon:+input.dataset.lon,label:input.dataset.label||input.value};if(norm(input.value)==='ma position'){const p=window.userPos||await gps();if(p)window.userPos=p;return p}try{const a=await searchPlace(input.value);return a?.[0]||null}catch(e){return null}}
async function walk(a,b){try{if(typeof foot==='function')return await foot(a,b)}catch(e){}const m=km(a,b)*1000;return{min:Math.max(1,Math.round(m/83)),m:Math.round(m)}}
function best(A,B){let best=null;for(const r of R){const aa=r.stops.map(s=>({...s,d:km(A,s)})).sort((a,b)=>a.d-b.d);const bb=r.stops.map(s=>({...s,d:km(B,s)})).sort((a,b)=>a.d-b.d);for(const a of aa.slice(0,3))for(const b of bb.slice(0,3)){if(a.i===b.i)continue;let d=0;const lo=Math.min(a.i,b.i),hi=Math.max(a.i,b.i);for(let i=lo;i<hi;i++)d+=km(r.stops[i],r.stops[i+1]);const score=a.d+b.d+d/10;if(!best||score<best.score)best={r,a,b,busMin:Math.max(3,Math.round(d/0.42)),score}}}return best}
async function calc(){go.disabled=true;go.textContent='Recherche…';result.innerHTML='<b>🔎 Recherche du meilleur trajet…</b><div class="small">Calcul en cours.</div>';try{const A=await point(document.getElementById('from')),B=await point(document.getElementById('to'));if(!A){result.innerHTML='<b class="err">📍 Position indisponible</b><div class="small">Appuie sur « Ma position » et autorise la localisation pour MauriMove.</div>';return}if(!B){result.innerHTML='<b class="err">📍 Destination introuvable</b><div class="small">Sélectionne une destination dans la liste.</div>';return}const c=best(A,B);if(!c){result.innerHTML='<b>Aucun trajet trouvé.</b>';return}const w1=await walk(A,c.a),w2=await walk(c.b,B),total=w1.min+c.busMin+w2.min;result.innerHTML='<div class="route"><div class="big">⭐ Ligne '+esc(c.r.ref)+'</div><div class="small">'+esc(c.r.from)+' → '+esc(c.r.to)+' · '+esc(c.r.operator)+'</div><div class="step">🚶 <b>'+esc(A.label||'Départ')+' → '+esc(c.a.name)+'</b><div class="small">'+w1.min+' min · '+w1.m+' m</div></div><div class="step">🚌 <b>'+esc(c.a.name)+' → '+esc(c.b.name)+'</b><div class="small">~'+c.busMin+' min · estimation</div></div><div class="step">🚶 <b>'+esc(c.b.name)+' → '+esc(B.label||'Destination')+'</b><div class="small">'+w2.min+' min · '+w2.m+' m</div></div><span class="badge" style="margin-top:9px">Direct · ~'+total+' min</span></div><div class="warn">ℹ️ Ligne 123 confirmée par les données CNT. Les durées sont indicatives : aucun ETA temps réel n’est inventé.</div>';if(typeof draw==='function')await draw(A,c.a,c.b,B)}catch(e){console.error(e);result.innerHTML='<b class="err">Impossible de calculer ce trajet.</b><div class="small">Réessaie avec une destination sélectionnée dans les suggestions.</div>'}finally{go.disabled=false;go.textContent='Trouver le meilleur trajet'}}
go.onclick=calc;window.calc=calc;
const gpsBtn=document.getElementById('gps');if(gpsBtn)gpsBtn.onclick=async()=>{gpsBtn.disabled=true;gpsBtn.textContent='⌖ Localisation…';const p=await gps();if(p){window.userPos=p;const f=document.getElementById('from');f.value='Ma position';delete f.dataset.lat;delete f.dataset.lon;gpsBtn.textContent='✓ Position trouvée';setTimeout(()=>{gpsBtn.textContent='⌖ Ma position';gpsBtn.disabled=false},1200)}else{gpsBtn.textContent='⚠️ Autorisation requise';setTimeout(()=>{gpsBtn.textContent='⌖ Ma position';gpsBtn.disabled=false},1800);result.innerHTML='<b class="err">📍 Localisation indisponible</b><div class="small">Vérifie l’autorisation de localisation de Safari.</div>'}};
})();