(()=>{
const go=document.getElementById('go'),result=document.getElementById('result');if(!go||!result)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=(a,b)=>Math.hypot((+a.lat-+b.lat)*111,(+a.lon-+b.lon)*104),walkMin=d=>Math.max(1,Math.round(d*1000/83)),key=(r,i)=>r+'|'+i;
let progressMarkers=[],liveWatch=null;
function sp(s,ri,i){return {lat:+s.lat,lon:+s.lon,label:s.name||s.stop_name||s.label||'Arrêt de bus',route:ri,i};}
function graph(){const nodes=new Map(),edges=new Map();
 routes.forEach((r,ri)=>r.stops.forEach((s,i)=>{const k=key(ri,i);nodes.set(k,{r:ri,i,s:sp(s,ri,i)});edges.set(k,[])}));
 routes.forEach((r,ri)=>{for(let i=0;i<r.stops.length-1;i++){const a=sp(r.stops[i],ri,i),b=sp(r.stops[i+1],ri,i+1);edges.get(key(ri,i)).push({to:key(ri,i+1),kind:'bus',min:Math.max(1,Math.round(km(a,b)*1000/420))});}});
 const all=[];routes.forEach((r,ri)=>r.stops.forEach((s,i)=>all.push(sp(s,ri,i))));
 for(const a of all)for(const b of all){if(a.route===b.route)continue;const d=km(a,b);if(d<=.45){const e=edges.get(key(a.route,a.i));if(e)e.push({to:key(b.route,b.i),kind:'transfer',min:walkMin(d)+2});}}
 return {nodes,edges};}
function nearest(p,limit=1.5){const out=[];routes.forEach((r,ri)=>r.stops.forEach((s,i)=>{const q=sp(s,ri,i),d=km(p,q);if(d<=limit)out.push({ri,i,p:q,d})}));return out.sort((a,b)=>a.d-b.d).slice(0,30);}
function routePlan(A,B){const g=graph(),starts=nearest(A),ends=nearest(B);if(!starts.length||!ends.length)return null;const dist=new Map(),prev=new Map(),q=[],endSet=new Set(ends.map(x=>key(x.ri,x.i)));starts.forEach(x=>{const k=key(x.ri,x.i),c=walkMin(x.d);if(c<(dist.get(k)??Infinity)){dist.set(k,c);q.push([c,k,0])}});let target=null;
 while(q.length){q.sort((a,b)=>a[0]-b[0]);const[d,u,t]=q.shift();if(d!==dist.get(u))continue;if(endSet.has(u)){target=u;break}if(t>3)continue;for(const e of g.edges.get(u)||[]){const nt=t+(e.kind==='transfer');if(nt>3)continue;const nd=d+e.min;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,{u,e});q.push([nd,e.to,nt]);}}}
 if(!target)return null;let chain=[],cur=target;while(cur){chain.push(cur);const p=prev.get(cur);if(!p)break;cur=p.u}chain.reverse();const end=ends.find(x=>key(x.ri,x.i)===target),first=g.nodes.get(chain[0]).s,last=g.nodes.get(chain.at(-1)).s;
 const segments=[{kind:'walk',from:A,to:first,min:walkMin(km(A,first)),m:Math.round(km(A,first)*1000)}];let leg=null;
 chain.forEach(k=>{const n=g.nodes.get(k);if(!leg||leg.route!==n.r){if(leg)segments.push(leg);leg={kind:'bus',route:n.r,stops:[n.s],min:0};}else leg.stops.push(n.s);});if(leg)segments.push(leg);
 for(let i=0;i<segments.length;i++)if(segments[i].kind==='bus'){const s=segments[i];s.min=Math.max(1,Math.round(s.stops.slice(0,-1).reduce((z,x,j)=>z+km(x,s.stops[j+1])*1000/420,0)));if(segments[i+1]?.kind==='bus'){const a=s.stops.at(-1),b=segments[i+1].stops[0];segments.splice(i+1,0,{kind:'transfer',from:a,to:b,min:walkMin(km(a,b)),m:Math.round(km(a,b)*1000)});i++;}}
 segments.push({kind:'walk',from:last,to:B,min:walkMin(km(last,B)),m:Math.round(km(last,B)*1000)});return {segments,totalMin:Math.round((dist.get(target)||0)+walkMin(end.d))};}
async function draw(plan){if(typeof clearMap==='function')clearMap();progressMarkers=[];const all=[];for(const s of plan.segments){if(s.kind==='bus'){const pts=s.stops.map(x=>[x.lat,x.lon]);let road=null;try{if(typeof realRoad==='function')road=await realRoad(pts)}catch{}all.push(...(road||pts));s.stops.forEach((x,i)=>{const m=L.circleMarker([x.lat,x.lon],{radius:5,weight:2,color:'#0072CE',fillColor:'#fff',fillOpacity:1}).addTo(map);m.bindTooltip((i+1)+' · '+x.label);progressMarkers.push(m);});}else all.push([s.from.lat,s.from.lon],[s.to.lat,s.to.lon]);}if(all.length>1)L.polyline(all,{color:'#0072CE',weight:6,opacity:.95,lineCap:'round',lineJoin:'round'}).addTo(map);map.fitBounds(L.latLngBounds(all),{padding:[70,70]});}
function render(plan){let h='<div class="route"><div class="big">⭐ Meilleur trajet · ~'+plan.totalMin+' min</div>';plan.segments.forEach(s=>{if(s.kind==='walk')h+='<div class="step">🚶 <b>'+esc(s.from.label)+' → '+esc(s.to.label)+'</b><div class="small">'+s.min+' min · '+s.m+' m</div></div>';else if(s.kind==='transfer')h+='<div class="step">🔄 <b>Correspondance</b><div class="small">🚶 '+s.min+' min · '+esc(s.from.label)+' → '+esc(s.to.label)+'</div></div>';else{const r=routes[s.route];h+='<div class="step"><span class="badge">🚌 Ligne '+esc(r.ref||'')+'</span> <b>'+esc(r.from||'')+' → '+esc(r.to||'')+'</b><div class="small">'+s.stops.length+' arrêts · ~'+s.min+' min</div></div>';}});h+='</div>';result.innerHTML=h;}
async function calc(){go.disabled=true;go.textContent='Recherche…';result.innerHTML='<b>🔎 Calcul de l’itinéraire…</b>';try{const A=await resolveInput($('from')),B=await resolveInput($('to'));if(!A||!B){result.innerHTML='<b class="err">📍 Départ ou destination introuvable.</b>';return}if(!routes?.length){result.innerHTML='<b class="err">Réseau bus indisponible.</b>';return}const p=routePlan(A,B);if(!p){result.innerHTML='<b>Aucun itinéraire trouvé.</b><div class="small">Aucun enchaînement de lignes à moins de 450 m entre les arrêts disponibles.</div>';return}await draw(p);render(p);}catch(e){console.error(e);result.innerHTML='<b class="err">Erreur de calcul</b><div class="small">'+esc(e.message||e)+'</div>'}finally{go.disabled=false;go.textContent='Trouver le meilleur trajet';}}
go.onclick=calc;window.calc=calc;
})();