(()=>{
const go=document.getElementById('go'),result=document.getElementById('result');
if(!go||!result)return;
const API='https://maurimove.meriamb.workers.dev/api/route';
let layers=[],markers=[],watch=null,currentPlan=null,currentStep=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=n=>Math.max(1,Math.round(Number(n)||0));
function clearMap(){layers.forEach(x=>{try{map.removeLayer(x)}catch{}});markers.forEach(x=>{try{map.removeLayer(x)}catch{}});layers=[];markers=[]}
function km(a,b){const lat=((+a.lat)+(+b.lat))/2*Math.PI/180;return Math.hypot((+a.lat-+b.lat)*110.57,(+a.lon-+b.lon)*111.32*Math.cos(lat))}
function walkMin(a,b){return Math.max(1,Math.round(km(a,b)*1000/83))}
async function walkRoad(a,b){try{const r=await fetch('https://valhalla1.openstreetmap.de/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:[{lat:+a.lat,lon:+a.lon},{lat:+b.lat,lon:+b.lon}],costing:'pedestrian',units:'kilometers',shape_format:'polyline6'})});if(!r.ok)throw Error();const j=await r.json(),s=j?.trip?.legs?.[0]?.shape;if(!s)return null;return decode6(s)}catch{return null}}
function decode6(s){let i=0,la=0,lo=0,o=[];while(i<s.length){let b,sh=0,r=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<sh;sh+=5}while(b>=32);la+=r&1?~(r>>1):r>>1;sh=0;r=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<sh;sh+=5}while(b>=32);lo+=r&1?~(r>>1):r>>1;o.push([la/1e6,lo/1e6])}return o}
async function driveRoad(points){if(points.length<2)return points.map(p=>[+p.lat,+p.lon]);try{const c=points.map(p=>`${+p.lon},${+p.lat}`).join(';'),r=await fetch(`https://router.project-osrm.org/route/v1/driving/${c}?overview=full&geometries=geojson&steps=false`);if(!r.ok)throw Error();const j=await r.json();return j?.routes?.[0]?.geometry?.coordinates?.map(p=>[p[1],p[0]])||points.map(p=>[+p.lat,+p.lon])}catch{return points.map(p=>[+p.lat,+p.lon])}}
function title(l){if(l.kind==='bus')return `🚌 Ligne ${esc(l.route_id||'?')}`;if(l.kind==='transfer')return '🔄 Correspondance';return '🚶 À pied'}
function labelPoint(p){return p?.name||p?.label||'Arrêt'}
async function draw(plan){clearMap();const all=[];for(const l of plan.legs){if(l.kind==='bus'){const pts=l.stops||[];pts.forEach((p,i)=>{const m=L.circleMarker([p.lat,p.lon],{radius:5,weight:2,color:'#0072CE',fillColor:'#fff',fillOpacity:1}).addTo(map);m.bindTooltip(`${i+1} · ${esc(labelPoint(p))}`);markers.push(m)});const line=await driveRoad(pts);all.push(...line);layers.push(L.polyline(line,{color:'#0072CE',weight:6,opacity:.95}).addTo(map))}else if(l.kind==='transfer'){const line=await walkRoad(l.from,l.to)||[[l.from.lat,l.from.lon],[l.to.lat,l.to.lon]];all.push(...line);layers.push(L.polyline(line,{color:'#475467',weight:4,opacity:.85,dashArray:'7 7'}).addTo(map))}else{const line=await walkRoad(l.from,l.to)||[[l.from.lat,l.from.lon],[l.to.lat,l.to.lon]];all.push(...line);layers.push(L.polyline(line,{color:'#475467',weight:5,opacity:.9,dashArray:'9 9'}).addTo(map))}}if(all.length)map.fitBounds(L.latLngBounds(all),{padding:[70,70]})}
function render(plan){currentPlan=plan;currentStep=0;const transfers=plan.legs.filter(l=>l.kind==='transfer').length;let h=`<div class="big">⭐ Meilleur trajet · ~${mins(plan.minutes)} min</div><div class="small">${transfers?`${transfers} correspondance${transfers>1?'s':''}`:'Trajet direct'} · horaires publiés</div><div class="warn">ℹ️ Temps indicatif : SegaMap utilise les horaires publiés. Il n’y a pas encore de GPS temps réel des bus.</div><button id="stepsBtn" class="btn" style="margin-top:10px;width:100%">🧭 Voir les étapes</button><div id="stepList" class="hidden">`;
plan.legs.forEach((l,i)=>{let d='';if(l.kind==='bus'){const a=l.stops?.[0],b=l.stops?.at(-1);d=`${esc(labelPoint(a))} → ${esc(labelPoint(b))} · ${l.stops.length} arrêts · ~${mins(l.minutes)} min`}else if(l.kind==='transfer'){d=`Marche · ~${mins(l.minutes)} min`}else{d=`Marche · ~${mins(l.minutes)} min · ${Math.round(l.meters||0)} m`}h+=`<button class="step stepChoice" data-step="${i}" style="width:100%;text-align:left;background:#fff;border:0;border-bottom:1px solid #eee"><b>${title(l)}</b><div class="small">${d}</div></button>`});h+='</div><button id="trackBtn" class="follow">📍 Suivre ma progression</button><div id="liveProgress" class="progress">Choisis une étape ou démarre le suivi GPS.</div>';result.innerHTML=h;document.getElementById('stepsBtn').onclick=()=>{const x=document.getElementById('stepList');x.classList.toggle('hidden');document.getElementById('stepsBtn').textContent=x.classList.contains('hidden')?'🧭 Voir les étapes':'🧭 Masquer les étapes'};document.querySelectorAll('.stepChoice').forEach(b=>b.onclick=()=>showStep(+b.dataset.step));document.getElementById('trackBtn').onclick=()=>startTracking()}
function showStep(i){if(!currentPlan)return;currentStep=Math.max(0,Math.min(i,currentPlan.legs.length-1));document.querySelectorAll('.stepChoice').forEach((b,j)=>{b.style.background=j===currentStep?'#eef6ff':'#fff';b.style.borderLeft=j===currentStep?'4px solid #0072CE':'4px solid transparent'});const l=currentPlan.legs[currentStep];const p=l.kind==='bus'?l.stops?.[0]:l.from; if(p)map.setView([p.lat,p.lon],15);const x=document.getElementById('liveProgress');if(x)x.innerHTML=`<b>Étape ${currentStep+1} / ${currentPlan.legs.length} :</b> ${title(l)}<br><span class="small">${l.kind==='bus'?`${esc(labelPoint(l.stops?.[0]))} → ${esc(labelPoint(l.stops?.at(-1)))}`:`${esc(labelPoint(l.from))} → ${esc(labelPoint(l.to))}`}</span>`}
function startTracking(){if(watch!==null)navigator.geolocation.clearWatch(watch);if(!navigator.geolocation){const x=document.getElementById('liveProgress');if(x)x.textContent='⚠️ Suivi GPS indisponible.';return}showStep(0);watch=navigator.geolocation.watchPosition(p=>{const l=currentPlan?.legs?.[currentStep];if(!l)return;const pos={lat:p.coords.latitude,lon:p.coords.longitude};const target=l.kind==='bus'?l.stops?.at(-1):l.to;if(target&&km(pos,target)<.09&&currentStep<currentPlan.legs.length-1)showStep(currentStep+1);const x=document.getElementById('liveProgress');if(x)x.innerHTML=`<b>📍 Étape ${currentStep+1} / ${currentPlan.legs.length}</b><br>${title(currentPlan.legs[currentStep])}<br><span class="small">GPS actif · pas d’ETA temps réel</span>`},()=>{const x=document.getElementById('liveProgress');if(x)x.textContent='⚠️ Suivi GPS indisponible. Vérifie la localisation Safari.'},{enableHighAccuracy:true,maximumAge:3000,timeout:12000})}
async function apiRoute(A,B){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:{lat:+A.lat,lon:+A.lon,name:A.label||A.name||'Départ'},to:{lat:+B.lat,lon:+B.lon,name:B.label||B.name||'Destination'})});const data=await r.json();if(!r.ok||!data.ok)throw Error(data.error||'Aucun itinéraire trouvé');return data}
async function calc(){go.disabled=true;go.textContent='Recherche…';result.innerHTML='<b>🔎 Recherche du meilleur trajet…</b><div class="small">Connexion au moteur SegaMap.</div>';try{const A=await resolveInput($('from')),B=await resolveInput($('to'));if(!A||!B)throw Error('Départ ou destination introuvable.');const data=await apiRoute(A,B);await draw(data);render(data)}catch(e){console.error(e);result.innerHTML=`<b class="err">Aucun itinéraire trouvé</b><div class="small">${esc(e.message||e)}</div>`}finally{go.disabled=false;go.textContent='Trouver le meilleur trajet'}}
go.onclick=calc;window.calc=calc;
})();