(()=>{
'use strict';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hav=(a,b)=>{const R=6371,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180,dla=(b.lat-a.lat)*Math.PI/180,dlo=(b.lon-a.lon)*Math.PI/180;const x=Math.sin(dla/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dlo/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
async function json(url,opt={},ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...opt,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function road(a,b){try{const u=`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=false`;const d=await json(u,{},10000);return d.routes?.[0]?.geometry?.coordinates?.map(p=>[p[1],p[0]])||[[a.lat,a.lon],[b.lat,b.lon]]}catch{return[[a.lat,a.lon],[b.lat,b.lon]]}}
function nearest(p,stops,limit=4){return stops.map((s,i)=>({s,i,d:hav(p,s)})).filter(x=>x.d<=limit).sort((a,b)=>a.d-b.d).slice(0,10)}
function makeGraph(rs){const nodes=new Map(),edges=[];const key=s=>s.id||`${s.lat.toFixed(5)},${s.lon.toFixed(5)}`;for(const r of rs){if(!r.stops||r.stops.length<2)continue;for(const s of r.stops){const k=key(s);if(!nodes.has(k))nodes.set(k,{key:k,lat:+s.lat,lon:+s.lon,name:s.name||'Arrêt',refs:new Set()});nodes.get(k).refs.add(String(r.ref));}for(let i=0;i<r.stops.length-1;i++){const a=r.stops[i],b=r.stops[i+1],ka=key(a),kb=key(b),d=hav(a,b);edges.push({a:ka,b:kb,d,kind:'bus',ref:String(r.ref),route:r,i});}}const arr=[...nodes.values()];for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const d=hav(arr[i],arr[j]);if(d<=0.35){edges.push({a:arr[i].key,b:arr[j].key,d,kind:'walk',ref:null});edges.push({a:arr[j].key,b:arr[i].key,d,kind:'walk',ref:null});}}return{nodes,edges}}
function dijkstra(g,start,end){const adj=new Map();for(const e of g.edges){if(!adj.has(e.a))adj.set(e.a,[]);adj.get(e.a).push(e);if(e.kind==='bus'){if(!adj.has(e.b))adj.set(e.b,[]);adj.get(e.b).push({...e,a:e.b,b:e.a});}}const distM=new Map([[start,0]]),prev=new Map(),q=new Set(g.nodes.keys());while(q.size){let u=null,best=Infinity;for(const k of q){const v=distM.get(k);if(v!==undefined&&v<best){best=v;u=k}}if(!u)break;q.delete(u);if(u===end)break;for(const e of (adj.get(u)||[])){const speed=e.kind==='walk'?4.5:22;const cost=e.d/speed*60+(e.kind==='walk'?0.5:3);const nd=best+cost;if(nd<(distM.get(e.b)??Infinity)){distM.set(e.b,nd);prev.set(e.b,{u,e})}}}if(!prev.has(end))return null;const out=[];let k=end;while(k!==start){const p=prev.get(k);if(!p)break;out.push(p.e);k=p.u}return out.reverse()}
function collapse(edges){const seg=[];for(const e of edges){if(e.kind==='bus'&&seg.length&&seg.at(-1).kind==='bus'&&seg.at(-1).ref===e.ref&&seg.at(-1).route===e.route&&seg.at(-1).i+1===e.i){seg.at(-1).end=e.b;seg.at(-1).toIndex=e.i+1}else seg.push({...e,start:e.a,end:e.b,toIndex:e.i+1})}return seg}
function nodeByKey(g,k){return g.nodes.get(k)}
async function drawTrip(trip){clearMap();const all=[];for(const s of trip.segments){const a=nodeByKey(trip.graph,s.start),b=nodeByKey(trip.graph,s.end);if(!a||!b)continue;if(s.kind==='bus'){const pts=await road(a,b);const line=L.polyline(pts,{color:'#0878d1',weight:6,opacity:.9}).addTo(map);layers.push(line);all.push(...pts)}else{const line=L.polyline([[a.lat,a.lon],[b.lat,b.lon]],{color:'#344054',weight:4,dashArray:'7 8',opacity:.8}).addTo(map);layers.push(line);all.push([a.lat,a.lon],[b.lat,b.lon])}}if(all.length)map.fitBounds(L.latLngBounds(all),{padding:[40,40]});}
function render(trip,from,to){const bus=trip.segments.filter(s=>s.kind==='bus'),changes=[];for(let i=1;i<bus.length;i++)if(bus[i].ref!==bus[i-1].ref)changes.push(bus[i-1].end);const first=bus[0]?.ref||'—';let html=`<div><span class="badge">${esc2(bus.length?bus.length+' ligne(s)':'Marche')}</span><h3 style="margin:8px 0">${esc2(from.label||'Départ')} → ${esc2(to.label||'Destination')}</h3>`;if(!bus.length)html+=`<div class="step">🚶 Aucun segment bus confirmé.</div>`;else bus.forEach((b,i)=>{const a=nodeByKey(trip.graph,b.start),z=nodeByKey(trip.graph,b.end);html+=`<div class="step"><b>🚌 Ligne ${esc2(b.ref)}</b><div class="small">${esc2(a?.name||'Arrêt')} → ${esc2(z?.name||'Arrêt')}</div>${i>0?'<div class="ok" style="margin-top:4px">🔄 Correspondance</div>':''}</div>`});html+=`<button id="followTrip" class="follow">📍 Suivre ma progression</button><div id="progressBox" class="progress">Le suivi affichera les arrêts passés et les prochains arrêts.</div>`;if(changes.length)html+=`<div class="warn">🔄 ${changes.length} correspondance(s) détectée(s).</div>`;html+='</div>';$('result').innerHTML=html;currentTrip=trip;$('followTrip').onclick=()=>startFollow(trip)}
function startFollow(trip){if(watchId!==null)navigator.geolocation.clearWatch(watchId);const box=$('progressBox');watchId=navigator.geolocation.watchPosition(p=>{userPos={lat:p.coords.latitude,lon:p.coords.longitude,label:'Ma position'};const buses=trip.segments.filter(s=>s.kind==='bus');let best=null;for(const s of buses){const r=s.route;if(!r?.stops)continue;const c=r.stops.map((x,i)=>({i,d:hav(userPos,x),s:x})).sort((a,b)=>a.d-b.d)[0];if(c&&(best===null||c.d<best.d))best={...c,ref:s.ref}}if(best){const upcoming=trip.graph&&buses.find(s=>String(s.ref)===String(best.ref))?.route?.stops?.slice(best.i,best.i+6)||[];box.innerHTML=`<b>🚌 Ligne ${esc2(best.ref)} — ${esc2(best.s.name)}</b><br><span class="small">${best.i===0?'Départ':best.i+' arrêt(s) passés'} · ${upcoming.length?upcoming.length-1:0} arrêt(s) à venir</span><div style="margin-top:7px">${upcoming.slice(0,5).map((s,i)=>`<div style="padding:4px 0">${i===0?'📍':'○'} ${esc2(s.name)}</div>`).join('')}</div>`;map.setView([userPos.lat,userPos.lon],15,{animate:true})}},()=>{box.textContent='Impossible de suivre la position. Vérifie l’autorisation de localisation.'},{enableHighAccuracy:true,maximumAge:5000,timeout:10000})}
async function routeGeneral(from,to){const rs=(routes||[]).filter(r=>r?.stops?.length>=2);const g=makeGraph(rs);if(!g.nodes.size)throw Error('Réseau indisponible');const starts=nearest(from,[...g.nodes.values()],3).map(x=>x.s||x);const ends=nearest(to,[...g.nodes.values()],3).map(x=>x.s||x);let best=null;for(const a of starts)for(const b of ends){const e=dijkstra(g,a.key,b.key);if(e){const walk=hav(from,a)+hav(b,to);const score=e.reduce((x,y)=>x+y.d,0)+walk*2;if(!best||score<best.score)best={edges:e,score,a,b}}}if(!best)throw Error('Aucun chemin dans le réseau cartographié');const seg=collapse(best.edges);return{graph:g,segments:seg,fromStop:best.a,toStop:best.b,walkStart:hav(from,best.a),walkEnd:hav(best.b,to),stops:seg.flatMap(s=>s.kind==='bus'?[...Array(Math.max(1,(s.toIndex-(s.route?.stops?.findIndex(x=>(x.id||`${x.lat.toFixed(5)},${x.lon.toFixed(5)}`)===s.start)||0))))].map(()=>null)]:[])} }
async function go(){const btn=$('go');btn.disabled=true;btn.textContent='Recherche…';$('result').innerHTML='<b>Recherche du meilleur trajet…</b><div class="small">Analyse des lignes et des correspondances.</div>';try{const from=await resolveInput($('from')),to=await resolveInput($('to'));if(!from||!to)throw Error('Sélectionne un départ et une destination.');const trip=await routeGeneral(from,to);await drawTrip(trip);render(trip,from,to)}catch(e){clearMap();$('result').innerHTML=`<b class="err">Aucun trajet bus confirmé.</b><div class="small">${esc2(e.message||'Impossible de calculer ce trajet.')}</div><div class="warn">Le moteur ne confirme que les lignes dont les arrêts sont réellement disponibles dans ses données.</div>`}finally{btn.disabled=false;btn.textContent='Trouver le meilleur trajet'}}
(async()=>{for(let i=0;i<40;i++){if(Array.isArray(routes)&&routes.length){$('status').textContent=`${routes.length} parcours chargés · moteur de correspondances actif`;break}await wait(500)}const old=$('go');if(old)old.onclick=go;const pick=$('pick');if(pick){pick.onclick=()=>{pickMode=!pickMode;pick.textContent=pickMode?'📍 Cliquez sur la carte':'📍 Carte';map.getContainer().style.cursor=pickMode?'crosshair':'';if(pickMode)$('status').textContent='Cliquez sur la carte pour choisir votre destination.'}}map.on('click',e=>{if(!pickMode)return;const i=$('to');i.value='Point sur la carte';i.dataset.lat=e.latlng.lat;i.dataset.lon=e.latlng.lng;i.dataset.label='Point sur la carte';pickMode=false;$('pick').textContent='📍 Carte';map.getContainer().style.cursor='';if(window.__pickMarker)map.removeLayer(window.__pickMarker);window.__pickMarker=L.marker(e.latlng).addTo(map).bindPopup('Destination sélectionnée').openPopup();});})();
})();
