(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hav=(a,b)=>{const R=6371,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180,dla=(b.lat-a.lat)*Math.PI/180,dlo=(b.lon-a.lon)*Math.PI/180;const x=Math.sin(dla/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dlo/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
const walkMin=d=>Math.max(1,Math.round(d/0.08));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function json(url,opt={},ms=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...opt,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function foot(a,b){const eps=[`https://routing.openstreetmap.de/routed-foot/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=false`,`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=false`];for(const u of eps)try{const d=await json(u,{},10000),c=d.routes?.[0]?.geometry?.coordinates;if(c?.length)return c.map(p=>[p[1],p[0]])}catch{}return [[a.lat,a.lon],[b.lat,b.lon]]}
async function busRoad(points){if(points.length<2)return points.map(p=>[p.lat,p.lon]);const out=[];for(let i=0;i<points.length-1;i+=24){const chunk=points.slice(i,Math.min(points.length,i+25));try{const u='https://router.project-osrm.org/route/v1/driving/'+chunk.map(p=>`${p.lon},${p.lat}`).join(';')+'?overview=full&geometries=geojson&steps=false';const d=await json(u,{},12000),c=d.routes?.[0]?.geometry?.coordinates;if(c?.length){const ll=c.map(p=>[p[1],p[0]]);out.push(...(out.length?ll.slice(1):ll));continue}}catch{}const ll=chunk.map(p=>[p.lat,p.lon]);out.push(...(out.length?ll.slice(1):ll))}return out}
function key(routeIndex,stopIndex){return `${routeIndex}|${stopIndex}`}
function makeGraph(rs){const nodes=new Map(),adj=new Map(),add=(k,n)=>{nodes.set(k,n);if(!adj.has(k))adj.set(k,[])};rs.forEach((r,ri)=>{if(!r?.stops||r.stops.length<2)return;r.stops.forEach((s,i)=>add(key(ri,i),{key:key(ri,i),ri,i,lat:+s.lat,lon:+s.lon,name:s.name||'Arrêt de bus',route:r}));for(let i=0;i<r.stops.length-1;i++){const a=nodes.get(key(ri,i)),b=nodes.get(key(ri,i+1)),d=hav(a,b),min=Math.max(1,Math.round(d/0.36));adj.get(a.key).push({to:b.key,kind:'bus',d,min,ri,i,j:i+1});adj.get(b.key).push({to:a.key,kind:'bus',d,min,ri,i:i+1,j:i})}});const arr=[...nodes.values()];for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const a=arr[i],b=arr[j];if(a.ri===b.ri)continue;const d=hav(a,b);if(d>0.45)continue;const min=walkMin(d)+1;adj.get(a.key).push({to:b.key,kind:'transfer',d,min,from:a,to:b});adj.get(b.key).push({to:a.key,kind:'transfer',d,min,from:b,to:a})}return{nodes,adj}}
function nearest(p,g,limit=1.5){return[...g.nodes.values()].map(n=>({...n,d:hav(p,n)})).filter(x=>x.d<=limit).sort((a,b)=>a.d-b.d).slice(0,28)}
function dijkstra(g,A,B){const starts=nearest(A,g),ends=nearest(B,g);if(!starts.length||!ends.length)return null;const endSet=new Map(ends.map(x=>[x.key,x])),dist=new Map(),prev=new Map(),q=[];for(const s of starts){const c=walkMin(s.d);if(c<(dist.get(s.key)??Infinity)){dist.set(s.key,c);q.push([c,s.key,0])}}let best=null;while(q.length){q.sort((a,b)=>a[0]-b[0]);const[c,u,changes]=q.shift();if(c!==dist.get(u))continue;if(endSet.has(u)){best={u,cost:c,end:endSet.get(u)};break}if(changes>4)continue;for(const e of g.adj.get(u)||[]){const nc=changes+(e.kind==='transfer'?1:0);if(nc>4)continue;const nd=c+e.min;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,{u,e});q.push([nd,e.to,nc])}}}if(!best)return null;const chain=[];let k=best.u;while(k){chain.unshift(k);const p=prev.get(k);if(!p)break;k=p.u}const segments=[];let busLeg=null;for(let i=1;i<chain.length;i++){const n=g.nodes.get(chain[i]),p=g.nodes.get(chain[i-1]);const edge=(g.adj.get(p.key)||[]).find(e=>e.to===n.key);if(!edge)continue;if(edge.kind==='bus'){if(!busLeg||busLeg.ri!==edge.ri){if(busLeg)segments.push(busLeg);busLeg={kind:'bus',ri:edge.ri,route:g.nodes.get(edge.to).route,indices:[p.i,n.i]}}else{busLeg.indices.push(n.i)}}else{if(busLeg){segments.push(busLeg);busLeg=null}segments.push({kind:'transfer',from:p,to:n,d:edge.d,min:edge.min})}}if(busLeg)segments.push(busLeg);return{segments,startStop:g.nodes.get(chain[0]),endStop:g.nodes.get(chain.at(-1)),cost:best.cost,walkStart:starts.find(x=>x.key===chain[0])?.d||0,walkEnd:best.end.d}}
function segmentStops(seg){if(seg.kind!=='bus')return[];const r=seg.route,start=seg.indices[0],end=seg.indices.at(-1),step=end>=start?1:-1,out=[];for(let i=start;step>0?i<=end:i>=end;i+=step){const s=r.stops[i];if(s)out.push({lat:+s.lat,lon:+s.lon,name:s.name||'Arrêt de bus',index:i})}return out}
function totalBusMin(seg){const ss=segmentStops(seg);let m=0;for(let i=0;i<ss.length-1;i++)m+=Math.max(1,Math.round(hav(ss[i],ss[i+1])/0.36));return m}
function clear(){if(typeof clearMap==='function')clear();else if(Array.isArray(window.layers)){layers.forEach(x=>{try{map.removeLayer(x)}catch{}});layers=[]}}
async function drawTrip(plan,A,B){clear();const all=[];const firstBus=plan.segments.find(s=>s.kind==='bus'),lastBus=[...plan.segments].reverse().find(s=>s.kind==='bus');if(firstBus){const p=segmentStops(firstBus)[0],w=await foot(A,p);layers.push(L.polyline(w,{color:'#475467',weight:4,dashArray:'7 8',opacity:.9}).addTo(map));all.push(...w)}for(const s of plan.segments){if(s.kind==='bus'){const pts=segmentStops(s),w=await busRoad(pts);layers.push(L.polyline(w,{color:'#0072CE',weight:6,opacity:.96,lineCap:'round',lineJoin:'round'}).addTo(map));all.push(...w);pts.forEach((p,i)=>{const m=L.circleMarker([p.lat,p.lon],{radius:4,weight:2,color:'#0072CE',fillColor:'#fff',fillOpacity:1}).addTo(map);m.bindTooltip(`${i+1} · ${p.name}`);layers.push(m)})}if(s.kind==='transfer'){const w=await foot(s.from,s.to);layers.push(L.polyline(w,{color:'#475467',weight:4,dashArray:'7 8',opacity:.9}).addTo(map));all.push(...w)}}if(lastBus){const p=segmentStops(lastBus).at(-1),w=await foot(p,B);layers.push(L.polyline(w,{color:'#475467',weight:4,dashArray:'7 8',opacity:.9}).addTo(map));all.push(...w)}else{const w=await foot(A,B);layers.push(L.polyline(w,{color:'#475467',weight:4,dashArray:'7 8',opacity:.9}).addTo(map));all.push(...w)}if(all.length)map.fitBounds(L.latLngBounds(all),{padding:[55,55]})}
function render(plan,A,B){const buses=plan.segments.filter(s=>s.kind==='bus'),changes=plan.segments.filter(s=>s.kind==='transfer');let busM=buses.reduce((n,s)=>n+totalBusMin(s),0),walkM=Math.round(plan.walkStart/0.08)+Math.round(plan.walkEnd/0.08)+changes.reduce((n,s)=>n+walkMin(s.d),0);let html=`<div><div class="big">⭐ Itinéraire recommandé · ~${busM+walkM} min <span class="small">(estimation, hors attente)</span></div><div class="small" style="margin:4px 0 10px">${esc(A.label||'Départ')} → ${esc(B.label||'Destination')}</div>`;if(plan.startStop&&plan.walkStart>0.02)html+=`<div class="step"><b>🚶 Marcher jusqu’à ${esc(plan.startStop.name)}</b><div class="small">${walkMin(plan.walkStart)} min · ${Math.round(plan.walkStart*1000)} m</div></div>`;buses.forEach((s,li)=>{const stops=segmentStops(s),r=s.route,from=stops[0],to=stops.at(-1);html+=`<div class="step"><span class="badge">🚌 Ligne ${esc(r.ref)}</span><div style="margin-top:5px"><b>${esc(from.name)} → ${esc(to.name)}</b></div><div class="small">${stops.length} arrêts · ~${totalBusMin(s)} min à bord · direction ${esc(r.to||r.from||'')}</div><details style="margin-top:7px"><summary style="cursor:pointer;font-weight:800">Voir les ${stops.length} arrêts</summary><div style="margin-top:5px">${stops.map((x,i)=>`<div style="padding:3px 0">${i===0?'🟢':i===stops.length-1?'🔴':'○'} ${i+1}. ${esc(x.name)}</div>`).join('')}</div></details></div>`;if(li<buses.length-1){const tr=changes[li],next=segmentStops(buses[li+1])[0];html+=`<div class="step"><b>🔄 Correspondance</b><div class="small">Descendre à ${esc(to.name)} puis marcher ${tr?walkMin(tr.d):'?'} min jusqu’à ${esc(next.name)}</div></div>`}});if(plan.endStop&&plan.walkEnd>0.02)html+=`<div class="step"><b>🚶 Dernière marche</b><div class="small">${walkMin(plan.walkEnd)} min · ${Math.round(plan.walkEnd*1000)} m jusqu’à ${esc(B.label||'destination')}</div></div>`;html+=`<div class="warn">⚠️ Les lignes et arrêts affichés proviennent des données de transport chargées par SegaMap. Les durées de bus sont des estimations basées sur la distance entre arrêts : elles ne remplacent pas l’horaire réel ni la position GPS du bus.</div><button id="followTrip" class="follow">📍 Suivre ma progression</button><div id="progressBox" class="progress">Active le suivi pour voir l’arrêt le plus proche et les prochains arrêts.</div></div>`;$('result').innerHTML=html;currentTrip=plan;$('followTrip').onclick=()=>startFollow(plan)}
function startFollow(plan){if(watchId!==null)navigator.geolocation.clearWatch(watchId);const box=$('progressBox');if(!navigator.geolocation){box.textContent='La géolocalisation n’est pas disponible.';return}watchId=navigator.geolocation.watchPosition(p=>{const pos={lat:p.coords.latitude,lon:p.coords.longitude};userPos={...pos,label:'Ma position'};const bs=plan.segments.filter(s=>s.kind==='bus');let best=null;bs.forEach((seg,li)=>segmentStops(seg).forEach((s,i)=>{const d=hav(pos,s);if(!best||d<best.d)best={d,s,i,seg,li}}));if(!best)return;const ss=segmentStops(best.seg),next=ss.slice(best.i+1,best.i+6);box.innerHTML=`<b>📍 Ligne ${esc(best.seg.route.ref)} · ${esc(best.s.name)}</b><br><span class="small">${best.i} arrêt${best.i>1?'s':''} passé${best.i>1?'s':''} · ${Math.max(0,ss.length-best.i-1)} à venir</span><div style="margin-top:7px">${next.map((s,i)=>`<div style="padding:4px 0">${i===0?'➡️':'○'} ${esc(s.name)}</div>`).join('')}</div>`;map.setView([pos.lat,pos.lon],15,{animate:true})},()=>box.textContent='Impossible de suivre la position. Vérifie l’autorisation de localisation.',{enableHighAccuracy:true,maximumAge:5000,timeout:10000})}
async function routeGeneral(from,to){const rs=(routes||[]).filter(r=>r?.stops?.length>=2);if(!rs.length)throw Error('Réseau de lignes indisponible.');const g=makeGraph(rs),p=dijkstra(g,from,to);if(!p)throw Error('Aucun chemin confirmé avec les arrêts et lignes actuellement cartographiés.');return p}
async function go(){const btn=$('go');btn.disabled=true;btn.textContent='Recherche…';$('result').innerHTML='<b>🔎 Recherche des correspondances…</b><div class="small">Analyse des lignes, arrêts, marche et correspondances.</div>';try{const from=await resolveInput($('from')),to=await resolveInput($('to'));if(!from||!to)throw Error('Sélectionne un départ et une destination.');const plan=await routeGeneral(from,to);await drawTrip(plan,from,to);render(plan,from,to)}catch(e){clear();$('result').innerHTML=`<b class="err">Aucun trajet confirmé.</b><div class="small">${esc(e.message||'Impossible de calculer ce trajet.')}</div><div class="warn">Le moteur n’invente pas de ligne : il utilise uniquement les parcours et arrêts effectivement chargés.</div>`}finally{btn.disabled=false;btn.textContent='Trouver le meilleur trajet'}}
(async()=>{for(let i=0;i<50;i++){if(Array.isArray(routes)&&routes.length){if($('status'))$('status').textContent=`${routes.length} parcours chargés · correspondances automatiques actives`;break}await wait(400)}const old=$('go');if(old)old.onclick=go;})();
})();