from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

replacements = {
    'href="./manifest.webmanifest?v=14"': 'href="./manifest.webmanifest?v=final9"',
    'href="./segamap-logo.svg?v=14"': 'href="./segamap-app-icon.svg?v=final9"',
    'src="./segamap-logo.svg?v=14"': 'src="./segamap-app-icon.svg?v=final9"',
    '<span class="name">SegaMap</span><span>🇲🇺</span>': '<span class="name">SegaMap</span>',
    '.brand{display:flex;align-items:center;gap:9px;font-size:28px;font-weight:950}': '.brand{display:flex;align-items:center;gap:9px;font-size:28px;font-weight:600;letter-spacing:-.4px}',
    '.go{width:100%;border:0;background:linear-gradient(90deg,#ef233c,#0072ce);color:#fff;border-radius:14px;padding:14px;margin-top:8px;font-weight:950;font-size:15px}': '.go{width:100%;border:0;background:linear-gradient(to bottom,#EA2839 0%,#EA2839 25%,#1A206D 25%,#1A206D 50%,#FFD500 50%,#FFD500 75%,#00A651 75%,#00A651 100%);color:#fff;border-radius:14px;padding:14px;margin-top:8px;font-weight:900;font-size:17px;text-shadow:0 1px 3px #0008;box-shadow:0 5px 14px #0002}',
    '<button class="btn" id="gps">⌖ Ma position</button>': '',
    '<button class="btn" id="pick">📍 Carte</button>': '',
    "$('gps').onclick=async()=>{const p=await locate();if(p){$('from').value='Ma position';delete $('from').dataset.lat;delete $('from').dataset.lon;L.circleMarker([p.lat,p.lon],{radius:8}).addTo(map).bindPopup('Ma position').openPopup()}};": '',
    "$('pick').onclick=()=>{pickMode=!pickMode;$('pick').textContent=pickMode?'📍 Cliquez sur la carte':'📍 Carte';map.getContainer().style.cursor=pickMode?'crosshair':''};": '',
    "map.on('click',e=>{if(!pickMode)return;const i=$('to');i.value='Point sur la carte';i.dataset.lat=e.latlng.lat;i.dataset.lon=e.latlng.lng;i.dataset.label='Point sur la carte';pickMode=false;$('pick').textContent='📍 Carte';L.marker(e.latlng).addTo(map).bindPopup('Destination').openPopup()});": '',
    'Trouver le meilleur trajet': 'Go',
    "go.textContent='Trouver le meilleur trajet'": "go.textContent='Go'",
    'await loadNLTA();await loadOSM();': 'await loadOSM();',
    "$('status').innerHTML='<span class=\"ok\">✓ '+routes.length+' parcours routables chargés · '+nltaCount+' lignes NLTA au catalogue</span>';": "$('status').innerHTML='<span class=\"ok\">✓ Réseau de transport disponible</span>';",
    '<div class="title">Réseau mauricien</div><div class="card"><span id="network" class="badge">Chargement…</span><div id="status" class="small" style="margin-top:7px">Chargement du réseau…</div></div>': '<div id="networkInfo" style="margin-top:10px;text-align:center;font-size:10px;color:#98A2B3"><span id="network">Réseau</span> · <span id="status">Chargement…</span></div>',
    "['Wolmar',-20.3125,57.362]": "['Wolmar',-20.30702,57.36722]",
}
for old, new in replacements.items():
    s = s.replace(old, new)

css = '''<style id="segamap-refined-mobile-css">
@media(max-width:760px){
html,body,#map{height:100dvh}
.panel{left:0!important;right:0!important;top:auto!important;bottom:0!important;width:100%!important;max-height:46dvh!important;height:auto!important;border-radius:24px 24px 0 0!important;padding:12px 12px calc(14px + env(safe-area-inset-bottom))!important;overflow:auto!important;box-shadow:0 -10px 38px #0003!important;z-index:3000!important}
.panel>.brand{display:none!important}.panel>.sub{display:none!important}
.refined-logo-final{position:fixed;left:50%;top:max(10px,env(safe-area-inset-top));transform:translateX(-50%);z-index:5000;display:flex;align-items:center;gap:8px;background:#fffffff2;backdrop-filter:blur(16px);border-radius:999px;padding:6px 13px 6px 8px;box-shadow:0 6px 22px #0003;pointer-events:none}
.refined-logo-final img{width:38px;height:38px;object-fit:contain}.refined-logo-final .name{font-size:23px;font-weight:600;letter-spacing:-.3px;color:#06143F}
.sub,.title{display:none!important}.actions{display:none!important}
.search-layout-final{display:grid;grid-template-columns:minmax(0,1fr) 62px;gap:8px;align-items:stretch}.search-layout-final .search{min-width:0}.search-rail-final{display:flex;flex-direction:column;gap:7px}.search-rail-final .btn,.search-rail-final .go{width:62px;height:50%;min-height:0;margin:0;padding:7px 3px;border-radius:14px}.search-rail-final .btn{background:#fff;border:1px solid #d0d5dd;font-size:11px;font-weight:850}.search-rail-final .go{font-size:0;background:linear-gradient(to bottom,#EA2839 0%,#EA2839 25%,#1A206D 25%,#1A206D 50%,#FFD500 50%,#FFD500 75%,#00A651 75%,#00A651 100%);color:#fff;text-shadow:0 1px 3px #0008}.search-rail-final .go:before{content:'➜';font-size:22px}.search-rail-final .go:after{content:'GO';display:block;font-size:9px;margin-top:1px}
.result-choice-final{display:block;width:100%;text-align:left;border:1px solid #e4e7ec;background:#fff;border-radius:17px;padding:13px;cursor:pointer;box-shadow:0 6px 18px #00000012}.mode-icons-final{display:flex;align-items:center;gap:6px;font-size:21px;overflow-x:auto;white-space:nowrap;padding-bottom:2px}.choice-title-final{font-size:14px;font-weight:900;margin-top:7px}.choice-meta-final{font-size:11px;color:#667085;margin-top:3px}
.route-screen-final{display:none}.route-screen-final.active{display:block;position:fixed;inset:0;z-index:4000;pointer-events:none}.route-back-final{position:absolute;left:13px;top:max(13px,env(safe-area-inset-top));z-index:4100;width:44px;height:44px;border:0;border-radius:50%;background:#fffffff5;box-shadow:0 6px 20px #0003;font-size:29px;line-height:40px;pointer-events:auto}.route-sheet-final{position:absolute;left:0;right:0;bottom:0;height:43dvh;min-height:300px;background:#fffffff8;backdrop-filter:blur(18px);border-radius:25px 25px 0 0;box-shadow:0 -12px 40px #0003;padding:12px 15px calc(12px + env(safe-area-inset-bottom));overflow:auto;pointer-events:auto}.route-grab-final{width:45px;height:5px;border-radius:99px;background:#d0d5dd;margin:0 auto 10px}.route-head-final{font-size:16px;font-weight:950}.route-sub-final{font-size:11px;color:#667085;margin:3px 0 5px}.route-step-final{display:flex;gap:10px;padding:10px 2px;border-bottom:1px solid #eef0f3;cursor:pointer}.route-step-final.active{background:#f3f8ff;border-radius:12px;padding-left:8px}.route-icon-final{width:34px;height:34px;border-radius:11px;background:#eef6ff;display:flex;align-items:center;justify-content:center;flex:none;font-size:18px}.route-main-final{min-width:0}.route-main-final b{font-size:13px}.route-main-final div{font-size:11px;color:#667085;margin-top:3px;line-height:1.35}.route-live-final{margin-top:8px;background:#eef6ff;border-radius:12px;padding:9px;font-size:11px}.route-follow-final{margin-top:8px;width:100%;border:0;background:#06143F;color:#fff;border-radius:12px;padding:11px;font-weight:900}
}
@media(min-width:761px){.refined-logo-final,.route-screen-final{display:none!important}}
</style>'''

js = '''<script id="segamap-refined-mobile-js">
(()=>{
const p=document.querySelector('.panel'),search=document.querySelector('.search'),go=document.querySelector('#go'),swap=document.querySelector('#swap'),result=document.querySelector('#result');
if(!p||!search||!go||!swap||!result)return;
const logo=document.createElement('div');logo.className='refined-logo-final';logo.innerHTML='<img src="./segamap-app-icon.svg?v=final9" alt="SegaMap"><span class="name">SegaMap</span>';document.body.appendChild(logo);
const oldGo=go.onclick;
const wrap=document.createElement('div');wrap.className='search-layout-final';const rail=document.createElement('div');rail.className='search-rail-final';search.parentNode.insertBefore(wrap,search);wrap.appendChild(search);rail.appendChild(swap);rail.appendChild(go);wrap.appendChild(rail);
const screen=document.createElement('div');screen.className='route-screen-final';screen.innerHTML='<button class="route-back-final" aria-label="Retour à la recherche">‹</button><div class="route-sheet-final"><div class="route-grab-final"></div><div id="routeContentFinal"></div></div>';document.body.appendChild(screen);
const content=screen.querySelector('#routeContentFinal');let meta=null,stepsFinal=[],geomsFinal=[],liveMarker=null,currentStepFinal=0;
const SOFITEL_STOP={lat:-20.30702,lon:57.36722,label:'Flic en Flac Public Beach / Wolmar'};
function escF(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function decode6(str){let i=0,lat=0,lon=0,out=[];while(i<str.length){let b,shift=0,res=0;do{b=str.charCodeAt(i++)-63;res|=(b&31)<<shift;shift+=5}while(b>=32);lat+=(res&1)?~(res>>1):(res>>1);shift=0;res=0;do{b=str.charCodeAt(i++)-63;res|=(b&31)<<shift;shift+=5}while(b>=32);lon+=(res&1)?~(res>>1):(res>>1);out.push([lat/1e6,lon/1e6])}return out}
async function walkLineF(a,b){try{const j=await getJSON('https://valhalla1.openstreetmap.de/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:[{lat:a.lat,lon:a.lon},{lat:b.lat,lon:b.lon}],costing:'pedestrian',units:'kilometers'})},12000);const sh=j.trip?.legs?.[0]?.shape;return sh?decode6(sh):null}catch{return null}}
async function buildStepsF(){const ss=segments(currentTrip.path),out=[];const first=ss[0]?.stops?.[0];if(first)out.push({type:'walk',icon:'🚶',title:'Marcher jusqu’à l’arrêt',detail:meta.A.label+' → '+first.name,a:meta.A,b:first});for(let i=0;i<ss.length;i++){const s=ss[i],a=s.stops[0],b=s.stops[s.stops.length-1];out.push({type:'bus',icon:'🚌',title:'Ligne '+s.route.ref,detail:a.name+' → '+b.name+' · '+Math.max(1,s.stops.length-1)+' arrêts',a,b,seg:s});if(i<ss.length-1){const n=ss[i+1].stops[0];out.push({type:'transfer',icon:'🔄',title:'Correspondance',detail:'Descendre à '+b.name+' · marcher jusqu’à la ligne '+ss[i+1].route.ref+' à '+n.name,a:b,b:n});}}const last=ss[ss.length-1]?.stops?.at(-1);if(last)out.push({type:'walk',icon:'🚶',title:'Marcher jusqu’à la destination',detail:last.name+' → '+meta.B.label,a:last,b:meta.B});return out}
function iconStrip(){return stepsFinal.map((s,i)=>'<span>'+s.icon+(s.type==='bus'?' '+escF(s.seg.route.ref):'')+'</span>'+((i<stepsFinal.length-1)?'<span style="color:#98A2B3">›</span>':'')).join('')}
async function prepareGeoms(){geomsFinal=[];for(const s of stepsFinal){let line=null;if(s.type==='bus')line=await roadLine(s.seg.stops)||s.seg.stops.map(p=>[p.lat,p.lon]);else line=await walkLineF(s.a,s.b)||[[s.a.lat,s.a.lon],[s.b.lat,s.b.lon]];geomsFinal.push(line)}}
function showStep(i){currentStepFinal=i;document.querySelectorAll('.route-step-final').forEach((e,j)=>e.classList.toggle('active',j===i));const s=stepsFinal[i],line=geomsFinal[i];if(!s||!line)return;clearMap();const poly=L.polyline(line,{weight:6,opacity:.96,dashArray:s.type==='bus'?null:'9 8'}).addTo(map);layers.push(poly);layers.push(L.marker([s.a.lat,s.a.lon]).addTo(map).bindPopup(s.title),L.marker([s.b.lat,s.b.lon]).addTo(map).bindPopup(s.detail));map.fitBounds(L.latLngBounds(line),{padding:[70,70]});if(liveMarker)liveMarker.bringToFront()}
function openRoute(){screen.classList.add('active');p.style.display='none';content.innerHTML='<div class="route-head-final">'+escF(meta.A.label)+' → '+escF(meta.B.label)+'</div><div class="route-sub-final">Appuie sur une étape pour voir précisément son parcours sur la carte.</div><div class="mode-icons-final" style="margin:4px 0 7px">'+iconStrip()+'</div><div id="routeStepsFinal"></div>';const list=content.querySelector('#routeStepsFinal');stepsFinal.forEach((s,i)=>{const el=document.createElement('div');el.className='route-step-final';el.innerHTML='<div class="route-icon-final">'+s.icon+'</div><div class="route-main-final"><b>'+escF(s.title)+'</b><div>'+escF(s.detail)+'</div></div>';el.onclick=()=>showStep(i);list.appendChild(el)});const follow=document.createElement('button');follow.className='route-follow-final';follow.textContent='📍 Suivre ma progression';list.appendChild(follow);follow.onclick=startLive;prepareGeoms().then(()=>showStep(0));setTimeout(()=>map.invalidateSize(),80)}
function startLive(){if(watchId!==null)return;watchId=navigator.geolocation.watchPosition(pos=>{userPos={lat:pos.coords.latitude,lon:pos.coords.longitude,label:'Ma position'};if(!liveMarker)liveMarker=L.circleMarker([userPos.lat,userPos.lon],{radius:8,weight:3}).addTo(map);else liveMarker.setLatLng([userPos.lat,userPos.lon]);let best=0,bestD=Infinity;geomsFinal.forEach((line,i)=>line.forEach(q=>{const d=Math.hypot((q[0]-userPos.lat)*110.57,(q[1]-userPos.lon)*104);if(d<bestD){bestD=d;best=i}}));if(best!==currentStepFinal)showStep(best);map.panTo([userPos.lat,userPos.lon],{animate:true});const live=content.querySelector('.route-live-final')||document.createElement('div');live.className='route-live-final';live.innerHTML='📍 <b>Vous êtes ici</b> · '+escF(stepsFinal[currentStepFinal]?.title||'');if(!live.parentNode)content.appendChild(live)},{enableHighAccuracy:true,maximumAge:4000,timeout:15000})}
screen.querySelector('.route-back-final').onclick=()=>{screen.classList.remove('active');p.style.display='block';setTimeout(()=>map.invalidateSize(),60)};
go.onclick=async function(){const fromInput=$('from');const isSofitel=norm(fromInput.value).includes('sofitel');const A=await resolveInput(fromInput),B=await resolveInput($('to'));if(isSofitel){fromInput.dataset.lat=SOFITEL_STOP.lat;fromInput.dataset.lon=SOFITEL_STOP.lon;fromInput.dataset.label=SOFITEL_STOP.label}meta={A,B};await oldGo.call(go);if(currentTrip&&A&&B){stepsFinal=await buildStepsF();result.innerHTML='<button class="result-choice-final" id="routeChoiceFinal"><div class="mode-icons-final">'+iconStrip()+'</div><div class="choice-title-final">'+escF(A.label)+' → '+escF(B.label)+'</div><div class="choice-meta-final">≈ '+currentTrip.minutes+' min · Appuyer pour voir le trajet</div></button>';result.querySelector('#routeChoiceFinal').onclick=e=>{e.stopPropagation();openRoute()}}};
})();
</script>'''

s = s.replace('</script></body>', '</script>' + css + js + '</body>')
p.write_text(s, encoding='utf-8')
